### ISSUE TITLE
UnicodeDecodeError when trying to run example

### ISSUE THREAD

**Issue by rmons01** [cabb99/open3spn2#11]
Hi, sorry if this is simple but I'm fairly new to python... I'm attempting to run the tutorial in a Jupyter notebook but in the first few lines I'm getting the following error:

UnicodeDecodeError:` 'charmap' codec can't decode byte 0x9d in position 6251: character maps to 'undefined'

`UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19464/3355266105.py in <module>
      2 # DNA type can be changed to 'A' or 'B'
      3 seq='ATACAAAGGTGCGAGGTTTCTATGCTCCCACG'
----> 4 dna=open3SPN2.DNA.fromSequence(seq,dna_type='B_curved')
      5 # Compute the topology for the DNA structure.
      6 # Since the dna was generated from the sequence using X3DNA,

~\Anaconda3\envs\py37\lib\site-packages\open3SPN2\ff3SPN2.py in fromSequence(cls, sequence, dna_type, output_pdb, temp_name, compute_topology)
    568         """ Initializes a DNA object from a DNA sequence """
    569         self = cls()
--> 570         self.parseConfigurationFile()
    571         sequence = pandas.Series([a for a in sequence], index=[('A', i) for i in range(len(sequence))])
    572         # Make a possible structure

~\Anaconda3\envs\py37\lib\site-packages\open3SPN2\ff3SPN2.py in parseConfigurationFile(self, configuration_file)
    157         self.configuration_file = configuration_file
    158         config = configparser.ConfigParser()
--> 159         config.read(configuration_file)
    160 
    161         # Parse all sections of the configuration file

~\Anaconda3\envs\py37\lib\configparser.py in read(self, filenames, encoding)
    694             try:
    695                 with open(filename, encoding=encoding) as fp:
--> 696                     self._read(fp, filename)
    697             except OSError:
    698                 continue

~\Anaconda3\envs\py37\lib\configparser.py in _read(self, fp, fpname)
   1012         indent_level = 0
   1013         e = None                              # None, or an exception
-> 1014         for lineno, line in enumerate(fp, start=1):
   1015             comment_start = sys.maxsize
   1016             # strip inline comments

~\Anaconda3\envs\py37\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6251: character maps to <undefined>
`

I'm not getting any errors after importing all the necessary libraries... and I believe I have X3DNA correctly installed and in my env.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 94.0.4606.81
 - Python v 3.7

Any help is greatly appreciated.

**Comment by cabb99** [comment]
Thank you for raising this issue. It seems the problem is that the file is being read using a wrong encoding. Can you try editing this file: `~\Anaconda3\envs\py37\lib\site-packages\open3SPN2\ff3SPN2.py` and changing line 159 from 
`config.read(configuration_file)` to `config.read(configuration_file, encoding='utf-8')`?
In windows the libraries should be located inside `C:\Users\<your-username>\Anaconda3\`

Let me know if that solves your problem.

**Comment by rmons01** [comment]
Hi, thanks for responding so quickly. So I've implemented the suggested change, but now have a new error:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7932/1772951633.py in <module>
      2 # DNA type can be changed to 'A' or 'B'
      3 seq='ATACAAAGGTGCGAGGTTTCTATGCTCCCACG'
----> 4 dna=open3SPN2.DNA.fromSequence(seq,dna_type='B_curved')
      5 # Compute the topology for the DNA structure.
      6 # Since the dna was generated from the sequence using X3DNA,

~\Anaconda3\envs\py37\lib\site-packages\open3SPN2\ff3SPN2.py in fromSequence(cls, sequence, dna_type, output_pdb, temp_name, compute_topology)
    571         sequence = pandas.Series([a for a in sequence], index=[('A', i) for i in range(len(sequence))])
    572         # Make a possible structure
--> 573         self.computeGeometry(sequence, temp_name=temp_name)
    574         self.DNAtype=dna_type
    575 

~\Anaconda3\envs\py37\lib\site-packages\open3SPN2\ff3SPN2.py in computeGeometry(self, sequence, temp_name)
    225             try:
    226                 subprocess.check_output([f'{location_x3dna}/bin/x3dna_utils',
--> 227                                          'cp_std', 'BDNA'])
    228                 subprocess.check_output([f'{location_x3dna}/bin/rebuild',
    229                                          '-atomic', f'{temp_name}_parameters.par',

~\Anaconda3\envs\py37\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    409 
    410     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 411                **kwargs).stdout
    412 
    413 

~\Anaconda3\envs\py37\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    486         kwargs['stderr'] = PIPE
    487 
--> 488     with Popen(*popenargs, **kwargs) as process:
    489         try:
    490             stdout, stderr = process.communicate(input, timeout=timeout)

~\Anaconda3\envs\py37\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

~\Anaconda3\envs\py37\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by rmons01** [comment]
Hm.. after checking to make sure it wasn't multiple python paths... I'm now getting the same error but a different comment at the end:

[WinError 193] %1 is not a valid Win32 application

**Comment by cabb99** [comment]
It seems it is trying the path of X3DNA but it can't find it or execute it. I usually run it in Linux, but I think the next step should be to make sure python can find the correct path to X3DNA and that it can execute it. Make sure you have installed X3DNA correctly: http://forum.x3dna.org/general-discussions/how-to-install-3dna-on-linux-and-windows/?PHPSESSID=09om8tenjb6deg5a6h8b7sar90

**Comment by rmons01** [comment]
Hi, I think that X3DNA (windows) is installed correctly as everything seems to check out as per the guide. I think the problem is that windows does not recognize some of the files in X3DNA... Do you think it could all work within a virtual machine running ubuntu? 

thanks again, looking forward to testing this out.

**Comment by cabb99** [comment]
yes, a virtual ubuntu machine should work. I can't help you with X3DNA on windows but maybe you can ask on their forums too.

**Comment by rmons01** [comment]
No worries. I should've expected problems after I read through their forums haha. 

I'm setting up a linux subsystem now to see if that will make things a little smoother. I'll report back if it works.
