### ISSUE TITLE
Add dependencies section to installation

### ISSUE THREAD

**Issue by jmoller93** [cabb99/open3spn2#2]
I am finding that my default versions of python, cuda, etc. computer do not meet the right dependencies for openMM or pdbfixer. 

I think it would be nice if you added a quick dependencies section to the installation guide so that users know what currently works. 

So far, I found that CUDA 10.2 and python 3.8 are too recent to be supported. I switched to python 3.7 with a `conda install python=3.7` and  am now able to install.

It might be nice to also add versions that you also notice that it works with.

**Comment by jmoller93** [comment]
Also, I realize how silly this is, but any version of X3DNA other than the current version (2.4) seem to not work with open3SPN2.

**Comment by cabb99** [comment]
Thank you for your feedback. I added the requirements on the README file.
