### ISSUE TITLE
Occupancy read error when there is blank

### ISSUE THREAD

**Issue by CryoSky** [cabb99/open3spn2#3]
https://github.com/cabb99/open3spn2/blob/fc5c4cf650b5b546e49907bf18f804ec3555f245/open3SPN2/ff3SPN2.py#L468-L469

The occupancy and temFactor could report error 'could not convert string to float' when there is blank.
Suggest to change like this:
occupancy=[0.0 if line[54:60].strip()=='' else float(line[54:60])],
tempFactor=[0.0 if line[60:66].strip()=='' else float(line[60:66])],

**Comment by cabb99** [comment]
Thank you, I changed it. 
I just removed the brackets, since we are expecting a single number.

**Comment by CryoSky** [comment]
There is still some error. When I tested, it shows "IndentationError: unexpected indent".
